FROM alpine:3.7 AS base
WORKDIR /src
RUN apk --update add alpine-sdk python3 bash ninja
RUN pip3 install --upgrade pip
RUN pip3 install meson
COPY . ./

# Debug
FROM base
RUN meson --buildtype=debug build
WORKDIR /src/build
RUN meson test

# Release
FROM base
RUN meson --buildtype=release build
WORKDIR /src/build
RUN meson test
